{% set name = "comtypes" %}
{% set version = "1.4.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/enthought/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 79bdb1e319a3e8cd26cf0aece54ff550aa0bb749625cf74c0cbe3cae2fe764d9

build:
  number: 0
  skip: true  # [not win or py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - clear_comtypes_cache = comtypes.clear_cache:main

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.0
  run:
    - python

# >           with winreg.OpenKey(winreg.HKEY_CLASSES_ROOT, rf"CLSID\{clsid}\TypeLib") as key:
                #  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# E           FileNotFoundError: [WinError 2] The system cannot find the file specified
{% set tests_to_skip = "test_clsid" %}
# E   OSError: [WinError -2147024703] %1 is not a valid Win32 application
{% set tests_to_skip = tests_to_skip + " or test_register_and_revoke" %}
{% set tests_to_skip = tests_to_skip + " or test_register_and_revoke_item_moniker" %}
# E       ImportError: cannot import name 'test_support' from 'test' (%PREFIX%\Lib\test\__init__.py)
{% set tests_to_skip = tests_to_skip + " or test_main" %}
# E   Windows fatal exception: access violation on win-arm64 (COM ShellLink Release)
{% set tests_to_skip = tests_to_skip + " or test_com_interface" %} # [win and arm64]

{% set ignored_win_arm64 = [
  "--deselect=comtypes/test/test_outparam.py::Test::test_c_char",
  "--ignore=comtypes/test/test_git.py",
  "--ignore=comtypes/test/test_malloc.py"
]%}

test:
  source_files:
    - comtypes/test
  imports:
    - comtypes
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - clear_comtypes_cache --help
    - pytest comtypes/test -k "not ({{ tests_to_skip }})" {{ ignored_win_arm64 | join(' ') }} # [win and arm64]
    - pytest comtypes/test -k "not ({{ tests_to_skip }})" # [not (win and arm64)]

about:
  home: https://github.com/enthought/comtypes
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: pure Python COM package
  description: |
    comtypes is a pure Python COM package based on the ctypes ffi foreign
    function library.The comtypes package makes it easy to access and implement
    both custom and dispatch based COM interfaces.While the pywin32 package
    contains superior client side support for dispatch based COM interfaces,it is
    not possible to access custom COM interfaces unless they are wrapped in
    C++-code.
  doc_url: https://pythonhosted.org/comtypes
  dev_url: https://github.com/enthought/comtypes

extra:
  recipe-maintainers:
    - nehaljwani
