travis:
  secure:
    BINSTAR_TOKEN: YdRFuugBdj5pO+V5ZmFFLNrLkp+KkjezkXefKC9UwezU65+OfcvcneLQvuXqqevF7JS7Je5NKiqWxt5TA/77MKKQvyCeFkK2pgSiQ2KWrSo61fibC3oNX3MjVxhEiwmyuZI6aS3UswCVLRSkNsFwquGtpYMHNEYc76prme9X4RY2mw6N50yNkarqn1FDW2na6RPkc+SX9YeWS7/BcskvH7xjCachaMKM/f74G2bUdpFduAo4qjCAq1rbv09C6UDAFbNjjxoI1UFvJe+ON6PyjCh3SUVgVi2BwRErzr3y61rVgqJ8rRC6lAlWybiD5HLnM6KWJCfyFx1XoBP4qFHlz52dqWX3V+iZeoLz6dBmimFMUoSx8BJz8HD7dcSVLul44dVFFY7Wj46uUAB9ekjQKoifFwFh3w7t+rXYNimW14Lat0j3QYsHhP/sc75g0UYV1Lt3wC62/i7y171JRLeTxyGppRjYHtYol92djWVR9avjvqTRFULZ/fbacDC2JgNjIM86jEojduC5tA/dsdWynGC0j+er/IhuRywX+zIcpWgyk5KcCiNhvXdeM6jsiX5M6Dg0D7orw44IjiVyx1fHD5zm48svYhwwbHezWXXVGYCs5hd6Ojr+V/pkGdiRKj4+xdkZTrNdkbOZJr9gmJzy2HOReBh0WkzqVYWYogw/h2o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
