appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: P3MXJ5KThbYYJbmGJpf7Nws7a4m9ojpQtCF5OISQa1BDKokXa1YoaFjqZ/gWyH+dQ04rBCCcyjSxjFwGzBWfwXRdObsJXlDXUhyIdxE27fxCwqcS9RrhaMYIwWoTLDtu2kYmLdZNGpZYSoTA6CL4aiH9/7BpW+4USU7Ygryf+6H/sL8Yt/9HbZ4loZDKeLKgBzhMRfQFGuzdhlX03KJv2zJG3Wb5bTmforhku7viH5+VXlYusuX5hK2eyOD8AGThKA1ugKfaUxA+YaIQu90Cn/Ol0EVOQhwV6pMm5t/xDX+CRtS/Ga1t4ARYIffNFR0+KU4kwsy3LKJZRNOocg4DwcvezCqPBQcRlawey2qg19ZNEjMVh4aH1+TnLFNNmp46/34XdpYjE/RtEpgX6jL4Hz0W4fAy+4DzWHkV4iwL9y78ZAI4jenCSLbnjC7P93mMkXRFbr69nGvtzJ4SV4a6d4tMm6wC9cX1y4unCgKYZ28rk43+eNr5dRcpelcD3boRsRTjCVfk47uOMgGFBIBhX8HpjYYKHOToKSD/vVHi6IYFr1Nx0cAffIgc78DCoIYXXfgTKNASuEFjseRb/vU1usvqn3oTd0UZK8K063nv3U1KiFl9eu793wnIOzfAxcJsZYOdUUy278tNmnGi+SS8NkwbM2CEpF2eJkAAOt2JSHA=}
